import fs from 'fs';
import path from 'path';
import {
  getModelForChain,
  preprocessVisitsForChain1,
  runEvidenceSplit,
  runSectionAssessment
} from '../src/llm/chains';
import { getWriteTerminologyRuntime } from '../src/rag/runtime';
import { DEFAULT_STUDY_CASE } from '../src/study/cases/defaultStudyCase';
import { buildStudySnapshotKey } from '../src/study/cases/studyCaseSnapshot';

/**
 * Runs preprocessing + CHAIN1 + CHAIN2 once on the fixed study EMR and stores
 * the result so every participant gets the same analysis without waiting.
 * Usage: npm run study:snapshot
 */
async function main() {
  // Same mapping as the /process route.
  const visits = DEFAULT_STUDY_CASE.visits.map((visit: any, idx: number) => ({
    index: visit.index ?? visit.visitIndex ?? idx + 1,
    date: visit.date ?? visit.visitDateTime ?? '',
    text: visit.soapText ?? visit.sanitizedText ?? ''
  }));

  const runtime = getWriteTerminologyRuntime();
  const startedAt = Date.now();
  const preprocessed = await preprocessVisitsForChain1(visits, {
    semanticMatcher: runtime.semanticMatcher,
    llmResolver: runtime.llmResolver
  });
  if (preprocessed.reviewRequired?.riskLevel === 'HIGH') {
    throw new Error('Study case was blocked by the HIGH de-identification risk gate.');
  }
  const preprocessMs = Date.now() - startedAt;

  const chain1StartedAt = Date.now();
  const evidenceCards = await runEvidenceSplit(preprocessed.preparedVisits);
  const chain1Ms = Date.now() - chain1StartedAt;

  const chain2StartedAt = Date.now();
  const sectionStates = await runSectionAssessment(evidenceCards);
  const chain2Ms = Date.now() - chain2StartedAt;

  const snapshot = {
    key: buildStudySnapshotKey(visits),
    generatedAt: new Date().toISOString(),
    models: { chain1: getModelForChain('chain1'), chain2: getModelForChain('chain2') },
    preprocessed,
    evidenceCards,
    sectionStates
  };

  const target = path.join(__dirname, '../src/study/cases/defaultStudyCaseAnalysis.generated.ts');
  fs.writeFileSync(
    target,
    [
      '// GENERATED by `npm run study:snapshot` (scripts/buildStudyCaseSnapshot.ts). Do not edit by hand.',
      `export const FIXED_STUDY_CASE_ANALYSIS: unknown = ${JSON.stringify(snapshot, null, 2)};`,
      ''
    ].join('\n'),
    'utf8'
  );

  console.log(
    `snapshot written: visits=${visits.length} clauses=${preprocessed.preparedVisits
      .map((visit: any) => visit.clauses.length)
      .join('/')} cards=${evidenceCards.length} pendingTerms=${preprocessed.pendingTermConfirmations.length}`
  );
  console.log(`timings: preprocess=${preprocessMs}ms chain1=${chain1Ms}ms chain2=${chain2Ms}ms`);
}

main()
  .then(() => process.exit(0))
  .catch((error) => {
    console.error(error);
    process.exit(1);
  });
