import fs from 'fs';
import path from 'path';
import { DEFAULT_STUDY_CASE, isFixedStudyCaseText } from '../src/study/cases/defaultStudyCase';
import { studyEmrTextHash } from '../src/study/cases/studyCaseFrozen';

/**
 * Freezes the processed result of one already-processed case so every study
 * participant gets exactly the same evidence cards, section states and AI
 * drafts for the fixed virtual-patient EMR.
 *
 * Pick a case whose drafts you have reviewed, then:
 *   npm run study:freeze -- <caseId> [apiBaseUrl]
 *
 * The case must hold the unmodified study EMR. Re-run this after the study EMR
 * changes; a frozen result for a different EMR text is ignored at runtime.
 */
const FROZEN_FIELDS = [
  'deidentifiedEMRs',
  'pendingTermConfirmations',
  'reviewRequired',
  'evidenceCards',
  'sectionStates',
  'sectionDrafts',
  'draftsBySection',
  'sectionEvidenceMap',
  'sectionStatusMap',
  'commonMissingItems',
  'commonQuestionSets',
  'sectionAdequacyReviews',
  'processingCache',
  'chainCache'
] as const;

async function main() {
  const caseId = process.argv[2];
  const baseUrl = (process.argv[3] || 'http://localhost:5000').replace(/\/$/, '');
  if (!caseId) throw new Error('Usage: npm run study:freeze -- <caseId> [apiBaseUrl]');

  const response = await fetch(`${baseUrl}/api/cases/${caseId}`);
  if (!response.ok) throw new Error(`Could not load case ${caseId}: HTTP ${response.status}`);
  const body: any = await response.json();
  const caseData: any = body.case || body;

  const texts: string[] = (caseData.visits || []).map((visit: any) => visit.soapText || '');
  if (!isFixedStudyCaseText(texts)) {
    throw new Error('This case does not hold the unmodified study EMR, so it cannot be frozen.');
  }
  if (!(caseData.sectionDrafts || []).some((draft: any) => draft?.draftText)) {
    throw new Error('This case has no AI drafts yet. Process it first.');
  }

  const fields: Record<string, unknown> = {};
  for (const key of FROZEN_FIELDS) fields[key] = caseData[key] ?? null;

  // Known term-normaliser defect: "약침 후" becomes "약침 치료 치료". The learner
  // compares evidence with the original record, so the original wording is kept.
  let repaired = 0;
  for (const card of (fields.evidenceCards as any[]) || []) {
    if (String(card?.normalizedText || '').includes('치료 치료')) {
      card.normalizedText = card.sourceText;
      repaired += 1;
    }
  }

  const frozen = {
    emrTextHash: studyEmrTextHash(DEFAULT_STUDY_CASE.visits.map((visit) => visit.soapText)),
    sourceCaseId: caseId,
    sourceExperimentCode: caseData.experiment_code || null,
    frozenAt: new Date().toISOString(),
    fields
  };

  const target = path.join(__dirname, '../src/study/cases/defaultStudyCaseProcessed.generated.ts');
  fs.writeFileSync(
    target,
    [
      '// GENERATED by `npm run study:freeze` (scripts/freezeStudyCase.ts). Do not edit by hand.',
      `export const FIXED_STUDY_CASE_PROCESSED: unknown = ${JSON.stringify(frozen, null, 2)};`,
      ''
    ].join('\n'),
    'utf8'
  );

  console.log(
    `frozen from ${caseId}: cards=${(fields.evidenceCards as any[]).length} ` +
      `drafts=${(fields.sectionDrafts as any[]).filter((draft) => draft?.draftText).length} ` +
      `repairedCards=${repaired}`
  );
}

if (require.main === module) {
  main()
    .then(() => process.exit(0))
    .catch((error) => {
      console.error(error);
      process.exit(1);
    });
}
